### ISSUE TITLE
MIT license infringement

### ISSUE THREAD

**Issue by luceos** [weezqyd/tenancy#1]
Hello Albert Leitato,

Thank you for forking my package [hyn/multi-tenant](https://github.com/tenancy/multi-tenant), it's a huge honor to see a fork that's been republished.

However, I'd like to point out that according to the MIT license you are required to keep my copyright and license notices, you can confirm this in your [own license](https://github.com/weezqyd/tenancy/blob/master/license.md). I'd also like to point out that merely redistributing someone else's code under a different name is not cool.

Thank you,

Daniël.

**Comment by weezqyd** [comment]
@luceos  accept my sincere apologies. I have reverted the license i will take down the project
